export type ComponentTier = "copy" | "lab";

export interface GalleryItem {
  id: string;
  slug: string;
  title: string;
  route: string;
  sourcePath: string;
  tier: ComponentTier;
  collection: string;
  preview:
    | "radial"
    | "dock"
    | "orb"
    | "ruler"
    | "minimap"
    | "video"
    | "table"
    | "rope"
    | "input"
    | "hud"
    | "gallery"
    | "upload"
    | "schedule"
    | "shader"
    | "studio";
  /** Live studio embed. The card links out; the shader stays on the tool page. */
  studio?: "silt" | "intaglio" | "phosphor" | "sumi";
  accent: string;
  isNew?: boolean;
  hasStaticPreview?: boolean;
}

export const galleryItems: GalleryItem[] = [
  {
    id: "bjork01",
    slug: "animated-radial-chart",
    title: "Animated radial chart",
    route: "/charts/animated-radial-chart",
    sourcePath: "components/bjork-ui/charts/animated-radial-chart.tsx",
    tier: "copy",
    collection: "Charts",
    preview: "radial",
    accent: "#ec5c13",
  },
  {
    id: "bjork02",
    slug: "message-dock",
    title: "Message dock",
    route: "/hud/message-dock",
    sourcePath: "components/bjork-ui/hud/message-dock.tsx",
    tier: "copy",
    collection: "Interactive",
    preview: "dock",
    accent: "#ec5c13",
  },
  {
    id: "bjork03",
    slug: "voice-powered-orb",
    title: "Voice powered orb",
    route: "/interactive/voice-powered-orb",
    sourcePath: "components/bjork-ui/interactive/voice-powered-orb.tsx",
    tier: "lab",
    collection: "Interactive",
    preview: "orb",
    accent: "#ec5c13",
  },
  {
    id: "bjork04",
    slug: "ruler-carousel",
    title: "Ruler carousel",
    route: "/galleries/ruler-carousel",
    sourcePath: "components/bjork-ui/galleries/ruler-carousel.tsx",
    tier: "copy",
    collection: "Galleries",
    preview: "ruler",
    accent: "#ec5c13",
  },
  {
    id: "bjork05",
    slug: "video-scroll-hero",
    title: "Video scroll hero",
    route: "/heroes/video-scroll-hero",
    sourcePath: "components/bjork-ui/heroes/video-scroll-hero.tsx",
    tier: "lab",
    collection: "Heroes",
    preview: "video",
    accent: "#ec5c13",
  },
  {
    id: "bjork06",
    slug: "financial-table",
    title: "Financial table",
    route: "/tables/financial-table",
    sourcePath: "components/bjork-ui/tables/financial-table.tsx",
    tier: "copy",
    collection: "Tables",
    preview: "table",
    accent: "#ec5c13",
  },
  {
    id: "bjork07",
    slug: "draggable-rope",
    title: "Draggable rope",
    route: "/interactive/draggable-rope",
    sourcePath: "components/bjork-ui/interactive/draggable-rope.tsx",
    tier: "lab",
    collection: "Interactive",
    preview: "rope",
    accent: "#ec5c13",
  },
  {
    id: "bjork09",
    slug: "hud-frame",
    title: "HUD frame",
    route: "/hud/base",
    sourcePath: "components/bjork-ui/hud/hud-frame.tsx",
    tier: "lab",
    collection: "HUD",
    preview: "hud",
    accent: "#ec5c13",
  },
  {
    id: "bjork10",
    slug: "portfolio-gallery",
    title: "Portfolio gallery",
    route: "/galleries/portfolio-gallery",
    sourcePath: "components/bjork-ui/galleries/portfolio-gallery.tsx",
    tier: "copy",
    collection: "Galleries",
    preview: "gallery",
    accent: "#ec5c13",
  },
  {
    id: "bjork11",
    slug: "video-upload-card",
    title: "Video upload card",
    route: "/cards/video-upload-card",
    sourcePath: "components/bjork-ui/cards/video-upload-card.tsx",
    tier: "copy",
    collection: "Cards",
    preview: "upload",
    accent: "#ec5c13",
  },
  {
    id: "bjork13",
    slug: "ai-voice-input",
    title: "AI voice input",
    route: "/ai/ai-voice-input",
    sourcePath: "components/bjork-ui/ai/ai-voice-input.tsx",
    tier: "copy",
    collection: "AI",
    preview: "input",
    accent: "#ec5c13",
  },
  {
    id: "bjork14",
    slug: "animated-status-badge",
    title: "Animated status badge",
    route: "/badges/animated-status-badge",
    sourcePath: "components/bjork-ui/badges/animated-status-badge.tsx",
    tier: "copy",
    collection: "Badges",
    preview: "hud",
    accent: "#ec5c13",
  },
  {
    id: "bjork15",
    slug: "animated-download",
    title: "Animated download",
    route: "/hud/animated-download",
    sourcePath: "components/bjork-ui/hud/animated-download.tsx",
    tier: "copy",
    collection: "HUD",
    preview: "upload",
    accent: "#ec5c13",
  },
  {
    id: "bjork16",
    slug: "animated-card-options",
    title: "Animated card options",
    route: "/cards/animated-card-options",
    sourcePath: "components/bjork-ui/cards/animated-card-options.tsx",
    tier: "copy",
    collection: "Cards",
    preview: "schedule",
    accent: "#ec5c13",
  },
  {
    id: "bjork17",
    slug: "animated-card-status-list",
    title: "Animated card status list",
    route: "/cards/animated-card-status-list",
    sourcePath: "components/bjork-ui/cards/animated-card-status-list.tsx",
    tier: "copy",
    collection: "Cards",
    preview: "schedule",
    accent: "#ec5c13",
  },
  {
    id: "bjork18",
    slug: "audio-upload-card",
    title: "Audio upload card",
    route: "/cards/audio-upload-card",
    sourcePath: "components/bjork-ui/cards/audio-upload-card.tsx",
    tier: "copy",
    collection: "Cards",
    preview: "upload",
    accent: "#ec5c13",
  },
  {
    id: "bjork19",
    slug: "bonuses-incentives-card",
    title: "Bonuses incentives card",
    route: "/cards/bonuses-incentives-card",
    sourcePath: "components/bjork-ui/cards/bonuses-incentives-card.tsx",
    tier: "copy",
    collection: "Cards",
    preview: "schedule",
    accent: "#ec5c13",
  },
  {
    id: "bjork20",
    slug: "coach-scheduling",
    title: "Coach scheduling",
    route: "/cards/coach-scheduling",
    sourcePath: "components/bjork-ui/cards/coach-scheduling-card.tsx",
    tier: "copy",
    collection: "Cards",
    preview: "schedule",
    accent: "#ec5c13",
  },
  {
    id: "bjork21",
    slug: "dashboard-card-modal",
    title: "Dashboard card modal",
    route: "/cards/dashboard-card-modal",
    sourcePath: "components/bjork-ui/cards/dashboard-card-modal.tsx",
    tier: "copy",
    collection: "Cards",
    preview: "hud",
    accent: "#ec5c13",
  },
  {
    id: "bjork22",
    slug: "event-countdown-card",
    title: "Event countdown card",
    route: "/cards/event-countdown-card",
    sourcePath: "components/bjork-ui/cards/event-countdown-card.tsx",
    tier: "copy",
    collection: "Cards",
    preview: "schedule",
    accent: "#ec5c13",
  },
  {
    id: "bjork23",
    slug: "hover-detail-card",
    title: "Hover detail card",
    route: "/cards/hover-detail-card",
    sourcePath: "components/bjork-ui/cards/hover-detail-card.tsx",
    tier: "copy",
    collection: "Cards",
    preview: "gallery",
    accent: "#ec5c13",
  },
  {
    id: "bjork24",
    slug: "news-cards",
    title: "News cards",
    route: "/cards/news-cards",
    sourcePath: "components/bjork-ui/cards/news-cards.tsx",
    tier: "copy",
    collection: "Cards",
    preview: "gallery",
    accent: "#ec5c13",
  },
  {
    id: "bjork25",
    slug: "onboarding-stages",
    title: "Onboarding stages",
    route: "/cards/onboarding-stages",
    sourcePath: "components/bjork-ui/cards/onboarding-stages.tsx",
    tier: "copy",
    collection: "Cards",
    preview: "schedule",
    accent: "#ec5c13",
  },
  {
    id: "bjork26",
    slug: "prediction-market-card",
    title: "Prediction market card",
    route: "/cards/prediction-market-card",
    sourcePath: "components/bjork-ui/cards/prediction-market-card.tsx",
    tier: "copy",
    collection: "Cards",
    preview: "table",
    accent: "#ec5c13",
  },
  {
    id: "bjork27",
    slug: "product-reveal-card",
    title: "Product reveal card",
    route: "/cards/product-reveal-card",
    sourcePath: "components/bjork-ui/cards/product-reveal-card.tsx",
    tier: "copy",
    collection: "Cards",
    preview: "gallery",
    accent: "#ec5c13",
  },
  {
    id: "bjork28",
    slug: "profile-hover-card",
    title: "Profile hover card",
    route: "/cards/profile-hover-card",
    sourcePath: "components/bjork-ui/cards/profile-hover-card.tsx",
    tier: "copy",
    collection: "Cards",
    preview: "gallery",
    accent: "#ec5c13",
  },
  {
    id: "bjork29",
    slug: "project-cards",
    title: "Project cards",
    route: "/cards/project-cards",
    sourcePath: "components/bjork-ui/cards/project-cards.tsx",
    tier: "copy",
    collection: "Cards",
    preview: "gallery",
    accent: "#ec5c13",
  },
  {
    id: "bjork31",
    slug: "gradient-selector",
    title: "Gradient selector",
    route: "/dropdowns/gradient-selector",
    sourcePath: "components/bjork-ui/dropdowns/gradient-selector.tsx",
    tier: "copy",
    collection: "Controls",
    preview: "input",
    accent: "#ec5c13",
  },
  {
    id: "bjork32",
    slug: "hover-image-gallery",
    title: "Hover image gallery",
    route: "/galleries/hover-image-gallery",
    sourcePath: "components/bjork-ui/galleries/hover-image-gallery.tsx",
    tier: "copy",
    collection: "Galleries",
    preview: "gallery",
    accent: "#ec5c13",
  },
  {
    id: "bjork33",
    slug: "reveal-text",
    title: "Reveal text",
    route: "/heroes/reveal-text",
    sourcePath: "components/bjork-ui/heroes/reveal-text.tsx",
    tier: "lab",
    collection: "Text",
    preview: "video",
    accent: "#ec5c13",
  },
  {
    id: "bjork34",
    slug: "glitchy-404",
    title: "Glitchy 404",
    route: "/hud/glitchy-404",
    sourcePath: "components/bjork-ui/hud/glitchy-404.tsx",
    tier: "lab",
    collection: "HUD",
    preview: "hud",
    accent: "#ec5c13",
  },
  {
    id: "bjork35",
    slug: "hud-2",
    title: "Overlay 2",
    route: "/hud/hud-2",
    sourcePath: "components/bjork-ui/hud/overlay-2.tsx",
    tier: "lab",
    collection: "HUD",
    preview: "hud",
    accent: "#ec5c13",
  },
  {
    id: "bjork36",
    slug: "hud-button",
    title: "HUD button",
    route: "/hud/hud-button",
    sourcePath: "components/bjork-ui/hud/hud-button.tsx",
    tier: "copy",
    collection: "HUD",
    preview: "hud",
    accent: "#ec5c13",
  },
  {
    id: "bjork37",
    slug: "hud-graph",
    title: "HUD graph",
    route: "/hud/hud-graph",
    sourcePath: "components/bjork-ui/hud/graph.tsx",
    tier: "lab",
    collection: "HUD",
    preview: "radial",
    accent: "#ec5c13",
  },
  {
    id: "bjork38",
    slug: "hud-status",
    title: "HUD status",
    route: "/hud/hud-status",
    sourcePath: "components/bjork-ui/hud/status.tsx",
    tier: "copy",
    collection: "HUD",
    preview: "hud",
    accent: "#ec5c13",
  },
  {
    id: "bjork40",
    slug: "warning-graphic",
    title: "Warning graphic",
    route: "/hud/warning-graphic",
    sourcePath: "components/bjork-ui/hud/warning.tsx",
    tier: "lab",
    collection: "HUD",
    preview: "hud",
    accent: "#ec5c13",
  },
  {
    id: "bjork89",
    slug: "periodic-table",
    title: "Periodic table",
    route: "/tables/periodic-table",
    sourcePath: "components/bjork-ui/tables/periodic-table.tsx",
    tier: "copy",
    collection: "Tables",
    preview: "table",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork43",
    slug: "contacts-table",
    title: "Contacts table",
    route: "/tables/contacts-table",
    sourcePath: "components/bjork-ui/tables/contacts-table.tsx",
    tier: "copy",
    collection: "Tables",
    preview: "table",
    accent: "#ec5c13",
  },
  {
    id: "bjork44",
    slug: "leads-table",
    title: "Leads table",
    route: "/tables/leads-table",
    sourcePath: "components/bjork-ui/tables/leads-table.tsx",
    tier: "copy",
    collection: "Tables",
    preview: "table",
    accent: "#ec5c13",
  },
  {
    id: "bjork45",
    slug: "resizable-table",
    title: "Resizable table",
    route: "/tables/resizable-table",
    sourcePath: "components/bjork-ui/tables/resizable-table.tsx",
    tier: "copy",
    collection: "Tables",
    preview: "table",
    accent: "#ec5c13",
  },
  {
    id: "bjork46",
    slug: "server-management",
    title: "Server management",
    route: "/tables/server-management",
    sourcePath: "components/bjork-ui/tables/server-management-table.tsx",
    tier: "copy",
    collection: "Tables",
    preview: "table",
    accent: "#ec5c13",
  },
  {
    id: "bjork47",
    slug: "primitive-accordion",
    title: "Accordion",
    route: "/primitives/accordion",
    sourcePath: "components/bjork-ui/primitives/accordion.tsx",
    tier: "copy",
    collection: "UI",
    preview: "input",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork48",
    slug: "primitive-alerts",
    title: "Alerts",
    route: "/primitives/alerts",
    sourcePath: "components/bjork-ui/primitives/alerts.tsx",
    tier: "copy",
    collection: "UI",
    preview: "hud",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork49",
    slug: "primitive-avatar",
    title: "Avatar",
    route: "/primitives/avatar",
    sourcePath: "components/bjork-ui/primitives/avatar.tsx",
    tier: "copy",
    collection: "UI",
    preview: "orb",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork50",
    slug: "primitive-badge",
    title: "Badge",
    route: "/primitives/badge",
    sourcePath: "components/bjork-ui/primitives/badge.tsx",
    tier: "copy",
    collection: "UI",
    preview: "hud",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork51",
    slug: "primitive-breadcrumb",
    title: "Breadcrumb",
    route: "/primitives/breadcrumb",
    sourcePath: "components/bjork-ui/primitives/breadcrumb.tsx",
    tier: "copy",
    collection: "UI",
    preview: "input",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork52",
    slug: "primitive-button",
    title: "Button",
    route: "/primitives/button",
    sourcePath: "components/bjork-ui/primitives/button.tsx",
    tier: "copy",
    collection: "UI",
    preview: "input",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork53",
    slug: "primitive-button-group",
    title: "Button Group",
    route: "/primitives/button-group",
    sourcePath: "components/bjork-ui/primitives/button-group.tsx",
    tier: "copy",
    collection: "UI",
    preview: "input",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork54",
    slug: "primitive-calendar",
    title: "Calendar",
    route: "/primitives/calendar",
    sourcePath: "components/bjork-ui/primitives/calendar.tsx",
    tier: "copy",
    collection: "UI",
    preview: "schedule",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork55",
    slug: "primitive-card",
    title: "Card",
    route: "/primitives/card",
    sourcePath: "components/bjork-ui/primitives/card.tsx",
    tier: "copy",
    collection: "UI",
    preview: "gallery",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork56",
    slug: "primitive-checkbox",
    title: "Checkbox",
    route: "/primitives/checkbox",
    sourcePath: "components/bjork-ui/primitives/checkbox.tsx",
    tier: "copy",
    collection: "UI",
    preview: "input",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork57",
    slug: "primitive-collapsible",
    title: "Collapsible",
    route: "/primitives/collapsible",
    sourcePath: "components/bjork-ui/primitives/collapsible.tsx",
    tier: "copy",
    collection: "UI",
    preview: "hud",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork58",
    slug: "primitive-combobox",
    title: "Combobox",
    route: "/primitives/combobox",
    sourcePath: "components/bjork-ui/primitives/combobox.tsx",
    tier: "copy",
    collection: "UI",
    preview: "input",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork59",
    slug: "primitive-data-table",
    title: "Data Table",
    route: "/primitives/data-table",
    sourcePath: "components/bjork-ui/primitives/data-table.tsx",
    tier: "copy",
    collection: "UI",
    preview: "table",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork60",
    slug: "primitive-date-picker",
    title: "Date Picker",
    route: "/primitives/date-picker",
    sourcePath: "components/bjork-ui/primitives/date-picker.tsx",
    tier: "copy",
    collection: "UI",
    preview: "schedule",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork61",
    slug: "primitive-dialog",
    title: "Dialog",
    route: "/primitives/dialog",
    sourcePath: "components/bjork-ui/primitives/dialog.tsx",
    tier: "copy",
    collection: "UI",
    preview: "hud",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork62",
    slug: "primitive-dropdown-menu",
    title: "Dropdown Menu",
    route: "/primitives/dropdown-menu",
    sourcePath: "components/bjork-ui/primitives/dropdown-menu.tsx",
    tier: "copy",
    collection: "UI",
    preview: "input",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork63",
    slug: "primitive-form",
    title: "Form",
    route: "/primitives/form",
    sourcePath: "components/bjork-ui/primitives/form.tsx",
    tier: "copy",
    collection: "UI",
    preview: "input",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork64",
    slug: "primitive-input",
    title: "Input",
    route: "/primitives/input",
    sourcePath: "components/bjork-ui/primitives/input.tsx",
    tier: "copy",
    collection: "UI",
    preview: "input",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork65",
    slug: "primitive-input-mask",
    title: "Input Mask",
    route: "/primitives/input-mask",
    sourcePath: "components/bjork-ui/primitives/input-mask.tsx",
    tier: "copy",
    collection: "UI",
    preview: "input",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork66",
    slug: "primitive-input-otp",
    title: "Input OTP",
    route: "/primitives/input-otp",
    sourcePath: "components/bjork-ui/primitives/input-otp.tsx",
    tier: "copy",
    collection: "UI",
    preview: "input",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork67",
    slug: "primitive-pagination",
    title: "Pagination",
    route: "/primitives/pagination",
    sourcePath: "components/bjork-ui/primitives/pagination.tsx",
    tier: "copy",
    collection: "UI",
    preview: "input",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork68",
    slug: "primitive-popover",
    title: "Popover",
    route: "/primitives/popover",
    sourcePath: "components/bjork-ui/primitives/popover.tsx",
    tier: "copy",
    collection: "UI",
    preview: "hud",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork69",
    slug: "primitive-radio-group",
    title: "Radio Group",
    route: "/primitives/radio-group",
    sourcePath: "components/bjork-ui/primitives/radio-group.tsx",
    tier: "copy",
    collection: "UI",
    preview: "input",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork70",
    slug: "primitive-select",
    title: "Select",
    route: "/primitives/select",
    sourcePath: "components/bjork-ui/primitives/select.tsx",
    tier: "copy",
    collection: "UI",
    preview: "input",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork71",
    slug: "primitive-sheet",
    title: "Sheet",
    route: "/primitives/sheet",
    sourcePath: "components/bjork-ui/primitives/sheet.tsx",
    tier: "copy",
    collection: "UI",
    preview: "hud",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork72",
    slug: "primitive-slider",
    title: "Slider",
    route: "/primitives/slider",
    sourcePath: "components/bjork-ui/primitives/slider.tsx",
    tier: "copy",
    collection: "UI",
    preview: "input",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork73",
    slug: "primitive-sonner",
    title: "Sonner",
    route: "/primitives/sonner",
    sourcePath: "components/bjork-ui/primitives/sonner.tsx",
    tier: "copy",
    collection: "UI",
    preview: "hud",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork74",
    slug: "primitive-switch",
    title: "Switch",
    route: "/primitives/switch",
    sourcePath: "components/bjork-ui/primitives/switch.tsx",
    tier: "copy",
    collection: "UI",
    preview: "input",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork75",
    slug: "primitive-table",
    title: "Table",
    route: "/primitives/table",
    sourcePath: "components/bjork-ui/primitives/table.tsx",
    tier: "copy",
    collection: "UI",
    preview: "table",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork76",
    slug: "primitive-tabs",
    title: "Tabs",
    route: "/primitives/tabs",
    sourcePath: "components/bjork-ui/primitives/tabs.tsx",
    tier: "copy",
    collection: "UI",
    preview: "input",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork77",
    slug: "primitive-textarea",
    title: "Textarea",
    route: "/primitives/textarea",
    sourcePath: "components/bjork-ui/primitives/textarea.tsx",
    tier: "copy",
    collection: "UI",
    preview: "input",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork78",
    slug: "primitive-tooltip",
    title: "Tooltip",
    route: "/primitives/tooltip",
    sourcePath: "components/bjork-ui/primitives/tooltip.tsx",
    tier: "copy",
    collection: "UI",
    preview: "hud",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork80",
    slug: "shader-aurora-veil",
    title: "Aurora veil",
    route: "/shaders/aurora-veil",
    sourcePath: "components/bjork-ui/shaders/website-shader.tsx",
    tier: "copy",
    collection: "Shaders",
    preview: "shader",
    accent: "#7bd8c4",
    hasStaticPreview: false,
  },
  {
    id: "bjork88",
    slug: "shader-kinetic-dots",
    title: "Kinetic dots",
    route: "/shaders/kinetic-dots",
    sourcePath: "components/bjork-ui/shaders/website-shader.tsx",
    tier: "copy",
    collection: "Shaders",
    preview: "shader",
    accent: "#f0d46a",
    hasStaticPreview: false,
  },
  {
    id: "bjork90",
    slug: "silt",
    title: "Silt",
    route: "https://isaiahbjork.com/silt",
    sourcePath: "",
    tier: "lab",
    collection: "Shaders",
    preview: "studio",
    studio: "silt",
    accent: "#ff5ea8",
    hasStaticPreview: false,
  },
  {
    id: "bjork91",
    slug: "intaglio",
    title: "Intaglio",
    route: "https://isaiahbjork.com/intaglio",
    sourcePath: "",
    tier: "lab",
    collection: "Shaders",
    preview: "studio",
    studio: "intaglio",
    accent: "#26823a",
    hasStaticPreview: false,
  },
  {
    id: "bjork92",
    slug: "phosphor",
    title: "Phosphor",
    route: "https://isaiahbjork.com/phosphor",
    sourcePath: "",
    tier: "lab",
    collection: "Shaders",
    preview: "studio",
    studio: "phosphor",
    accent: "#ffb070",
    hasStaticPreview: false,
  },
  {
    id: "bjork114",
    slug: "sumi",
    title: "Sumi",
    route: "https://isaiahbjork.com/sumi",
    sourcePath: "",
    tier: "lab",
    collection: "Shaders",
    preview: "studio",
    studio: "sumi",
    accent: "#2f43cf",
    hasStaticPreview: false,
  },
  {
    id: "bjork93",
    slug: "timer",
    title: "Timer",
    route: "/misc/timer",
    sourcePath: "components/bjork-ui/misc/timer.tsx",
    tier: "copy",
    collection: "Interactive",
    preview: "radial",
    accent: "#ffc107",
  },
  {
    id: "bjork115",
    slug: "project-index",
    title: "Project index",
    route: "/galleries/project-index",
    sourcePath: "components/bjork-ui/galleries/project-index.tsx",
    tier: "copy",
    collection: "Galleries",
    preview: "gallery",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork119",
    slug: "glow-rules",
    title: "Glow rules",
    route: "/misc/glow-rules",
    sourcePath: "components/bjork-ui/misc/glow-rules.tsx",
    tier: "copy",
    collection: "Utilities",
    preview: "table",
    accent: "#ededed",
    isNew: true,
  },

  {
    id: "bjork94",
    slug: "radial-command-ring",
    title: "Radial command ring",
    route: "/navigation/radial-command-ring",
    sourcePath: "components/bjork-ui/navigation/radial-command-ring.tsx",
    tier: "copy",
    collection: "Navigation",
    preview: "input",
    accent: "#ec5c13",
    isNew: true,
  },

  {
    id: "bjork95",
    slug: "adaptive-precision-slider",
    title: "Adaptive precision slider",
    route: "/controls/adaptive-precision-slider",
    sourcePath: "components/bjork-ui/controls/adaptive-precision-slider.tsx",
    tier: "copy",
    collection: "Controls",
    preview: "input",
    accent: "#ec5c13",
    isNew: true,
  },

  {
    id: "bjork96",
    slug: "click-wheel",
    title: "Click wheel",
    route: "/controls/click-wheel",
    sourcePath: "components/bjork-ui/controls/click-wheel.tsx",
    tier: "copy",
    collection: "Controls",
    preview: "input",
    accent: "#ec5c13",
    isNew: true,
  },

  {
    id: "bjork97",
    slug: "velocity-ink",
    title: "Velocity ink",
    route: "/controls/velocity-ink",
    sourcePath: "components/bjork-ui/controls/velocity-ink.tsx",
    tier: "copy",
    collection: "Controls",
    preview: "input",
    accent: "#ec5c13",
    isNew: true,
  },

  {
    id: "bjork98",
    slug: "spring-tuner",
    title: "Spring tuner",
    route: "/utilities/spring-tuner",
    sourcePath: "components/bjork-ui/utilities/spring-tuner.tsx",
    tier: "copy",
    collection: "Utilities",
    preview: "input",
    accent: "#ec5c13",
    isNew: true,
  },

  {
    id: "bjork99",
    slug: "live-line",
    title: "Live line",
    route: "/charts/live-line",
    sourcePath: "components/bjork-ui/charts/live-line.tsx",
    tier: "copy",
    collection: "Charts",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },

  {
    id: "bjork100",
    slug: "flap-ledger",
    title: "Flap ledger",
    route: "/tables/flap-ledger",
    sourcePath: "components/bjork-ui/tables/flap-ledger.tsx",
    tier: "copy",
    collection: "Tables",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },

  {
    id: "bjork101",
    slug: "route-trace",
    title: "Route trace",
    route: "/charts/route-trace",
    sourcePath: "components/bjork-ui/charts/route-trace.tsx",
    tier: "copy",
    collection: "Charts",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },

  {
    id: "bjork102",
    slug: "solar-sky-panel",
    title: "Solar sky panel",
    route: "/cards/solar-sky-panel",
    sourcePath: "components/bjork-ui/cards/solar-sky-panel.tsx",
    tier: "copy",
    collection: "Cards",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },

  {
    id: "bjork103",
    slug: "agent-trace",
    title: "Agent trace",
    route: "/ai/agent-trace",
    sourcePath: "components/bjork-ui/ai/agent-trace.tsx",
    tier: "copy",
    collection: "AI",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },

  {
    id: "bjork104",
    slug: "handoff-beam",
    title: "Handoff beam",
    route: "/ai/handoff-beam",
    sourcePath: "components/bjork-ui/ai/handoff-beam.tsx",
    tier: "lab",
    collection: "AI",
    preview: "orb",
    accent: "#ec5c13",
    isNew: true,
  },

  {
    id: "bjork105",
    slug: "lattice-orb",
    title: "Lattice orb",
    route: "/ai/lattice-orb",
    sourcePath: "components/bjork-ui/ai/lattice-orb.tsx",
    tier: "lab",
    collection: "AI",
    preview: "orb",
    accent: "#ec5c13",
    isNew: true,
  },

  {
    id: "bjork106",
    slug: "torn-edge-reveal",
    title: "Torn edge reveal",
    route: "/galleries/torn-edge-reveal",
    sourcePath: "components/bjork-ui/galleries/torn-edge-reveal.tsx",
    tier: "copy",
    collection: "Galleries",
    preview: "gallery",
    accent: "#ec5c13",
    isNew: true,
  },

  {
    id: "bjork107",
    slug: "mosaic-settle",
    title: "Mosaic settle",
    route: "/galleries/mosaic-settle",
    sourcePath: "components/bjork-ui/galleries/mosaic-settle.tsx",
    tier: "lab",
    collection: "Galleries",
    preview: "gallery",
    accent: "#ec5c13",
    isNew: true,
  },

  {
    id: "bjork108",
    slug: "minimap-scrollbar",
    title: "Minimap scrollbar",
    route: "/navigation/minimap-scrollbar",
    sourcePath: "components/bjork-ui/navigation/minimap-scrollbar.tsx",
    tier: "copy",
    collection: "Navigation",
    preview: "minimap",
    accent: "#ec5c13",
    isNew: true,
  },

  {
    id: "bjork109",
    slug: "morph-loader",
    title: "Morph loader",
    route: "/feedback/morph-loader",
    sourcePath: "components/bjork-ui/feedback/morph-loader.tsx",
    tier: "copy",
    collection: "Feedback",
    preview: "input",
    accent: "#ec5c13",
    isNew: true,
  },

  {
    id: "bjork110",
    slug: "stroke-morph-icon",
    title: "Stroke-morph icon",
    route: "/utilities/stroke-morph-icon",
    sourcePath: "components/bjork-ui/utilities/stroke-morph-icon.tsx",
    tier: "copy",
    collection: "Utilities",
    preview: "input",
    accent: "#ec5c13",
    isNew: true,
  },

  {
    id: "bjork111",
    slug: "scatter-rewind",
    title: "Scatter rewind",
    route: "/text/scatter-rewind",
    sourcePath: "components/bjork-ui/text/scatter-rewind.tsx",
    tier: "lab",
    collection: "Text",
    preview: "input",
    accent: "#ec5c13",
    isNew: true,
  },

  {
    id: "bjork112",
    slug: "plane-type",
    title: "Plane type",
    route: "/text/plane-type",
    sourcePath: "components/bjork-ui/text/plane-type.tsx",
    tier: "copy",
    collection: "Text",
    preview: "input",
    accent: "#ec5c13",
    isNew: true,
  },

  {
    id: "bjork113",
    slug: "elastic-frame",
    title: "Elastic frame",
    route: "/interactive/elastic-frame",
    sourcePath: "components/bjork-ui/interactive/elastic-frame.tsx",
    tier: "copy",
    collection: "Interactive",
    preview: "input",
    accent: "#ec5c13",
    isNew: true,
  },

  {
    id: "bjork116",
    slug: "aperture-dive",
    title: "Aperture dive",
    route: "/heroes/aperture-dive",
    sourcePath: "components/bjork-ui/heroes/aperture-dive.tsx",
    tier: "copy",
    collection: "Heroes",
    preview: "video",
    accent: "#ffe9cc",
    isNew: true,
  },
  {
    id: "bjork117",
    slug: "scene-states",
    title: "Scene states",
    route: "/interactive/scene-states",
    sourcePath: "components/bjork-ui/interactive/scene-states-demo.tsx",
    tier: "copy",
    collection: "Interactive",
    preview: "video",
    accent: "#7cc4ff",
    isNew: true,
  },

  {
    id: "bjork120",
    slug: "sortable-table",
    title: "Sortable table",
    route: "/tables/sortable-table",
    sourcePath: "components/bjork-ui/tables/sortable-table.tsx",
    tier: "copy",
    collection: "Tables",
    preview: "table",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork121",
    slug: "pricing-table",
    title: "Pricing table",
    route: "/tables/pricing-table",
    sourcePath: "components/bjork-ui/tables/pricing-table.tsx",
    tier: "copy",
    collection: "Tables",
    preview: "table",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork122",
    slug: "invoice-table",
    title: "Invoice table",
    route: "/tables/invoice-table",
    sourcePath: "components/bjork-ui/tables/invoice-table.tsx",
    tier: "copy",
    collection: "Tables",
    preview: "table",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork123",
    slug: "leaderboard-table",
    title: "Leaderboard",
    route: "/tables/leaderboard-table",
    sourcePath: "components/bjork-ui/tables/leaderboard-table.tsx",
    tier: "copy",
    collection: "Tables",
    preview: "table",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork124",
    slug: "changelog-table",
    title: "Changelog table",
    route: "/tables/changelog-table",
    sourcePath: "components/bjork-ui/tables/changelog-table.tsx",
    tier: "copy",
    collection: "Tables",
    preview: "table",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork125",
    slug: "api-reference-table",
    title: "API reference table",
    route: "/tables/api-reference-table",
    sourcePath: "components/bjork-ui/tables/api-reference-table.tsx",
    tier: "copy",
    collection: "Tables",
    preview: "table",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork126",
    slug: "file-tree-table",
    title: "File tree table",
    route: "/tables/file-tree-table",
    sourcePath: "components/bjork-ui/tables/file-tree-table.tsx",
    tier: "copy",
    collection: "Tables",
    preview: "table",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork127",
    slug: "timetable",
    title: "Timetable",
    route: "/tables/timetable",
    sourcePath: "components/bjork-ui/tables/timetable.tsx",
    tier: "copy",
    collection: "Tables",
    preview: "table",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork128",
    slug: "shortcuts-table",
    title: "Shortcuts table",
    route: "/tables/shortcuts-table",
    sourcePath: "components/bjork-ui/tables/shortcuts-table.tsx",
    tier: "copy",
    collection: "Tables",
    preview: "table",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork129",
    slug: "spec-sheet",
    title: "Spec sheet",
    route: "/tables/spec-sheet",
    sourcePath: "components/bjork-ui/tables/spec-sheet.tsx",
    tier: "copy",
    collection: "Tables",
    preview: "table",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork130",
    slug: "transactions-table",
    title: "Transactions table",
    route: "/tables/transactions-table",
    sourcePath: "components/bjork-ui/tables/transactions-table.tsx",
    tier: "copy",
    collection: "Tables",
    preview: "table",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork131",
    slug: "spreadsheet-grid",
    title: "Spreadsheet grid",
    route: "/tables/spreadsheet-grid",
    sourcePath: "components/bjork-ui/tables/spreadsheet-grid.tsx",
    tier: "copy",
    collection: "Tables",
    preview: "table",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork132",
    slug: "permissions-matrix",
    title: "Permissions matrix",
    route: "/tables/permissions-matrix",
    sourcePath: "components/bjork-ui/tables/permissions-matrix.tsx",
    tier: "copy",
    collection: "Tables",
    preview: "table",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork133",
    slug: "glyph-morph",
    title: "Glyph morph",
    route: "/text/glyph-morph",
    sourcePath: "components/bjork-ui/text/glyph-morph.tsx",
    tier: "copy",
    collection: "Text",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork134",
    slug: "weight-wave",
    title: "Weight wave",
    route: "/text/weight-wave",
    sourcePath: "components/bjork-ui/text/weight-wave.tsx",
    tier: "copy",
    collection: "Text",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork135",
    slug: "decode-text",
    title: "Decode text",
    route: "/text/decode-text",
    sourcePath: "components/bjork-ui/text/decode-text.tsx",
    tier: "copy",
    collection: "Text",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork136",
    slug: "magnetic-letters",
    title: "Magnetic letters",
    route: "/text/magnetic-letters",
    sourcePath: "components/bjork-ui/text/magnetic-letters.tsx",
    tier: "copy",
    collection: "Text",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork137",
    slug: "slice-shift",
    title: "Slice shift",
    route: "/text/slice-shift",
    sourcePath: "components/bjork-ui/text/slice-shift.tsx",
    tier: "copy",
    collection: "Text",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork138",
    slug: "stroke-draw-type",
    title: "Stroke draw type",
    route: "/text/stroke-draw-type",
    sourcePath: "components/bjork-ui/text/stroke-draw-type.tsx",
    tier: "copy",
    collection: "Text",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork139",
    slug: "ink-bleed-text",
    title: "Ink bleed text",
    route: "/text/ink-bleed-text",
    sourcePath: "components/bjork-ui/text/ink-bleed-text.tsx",
    tier: "copy",
    collection: "Text",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork140",
    slug: "liquid-text",
    title: "Liquid text",
    route: "/text/liquid-text",
    sourcePath: "components/bjork-ui/text/liquid-text.tsx",
    tier: "copy",
    collection: "Text",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork202",
    slug: "marketing-hero-product",
    title: "Marketing hero with product shot",
    route: "/blocks/marketing-hero-product",
    sourcePath: "components/bjork-ui/blocks/marketing-hero-product.tsx",
    tier: "copy",
    collection: "Blocks",
    preview: "gallery",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork203",
    slug: "marketing-feature-bento",
    title: "Marketing feature bento",
    route: "/blocks/marketing-feature-bento",
    sourcePath: "components/bjork-ui/blocks/marketing-feature-bento.tsx",
    tier: "copy",
    collection: "Blocks",
    preview: "gallery",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork204",
    slug: "marketing-pricing",
    title: "Marketing pricing",
    route: "/blocks/marketing-pricing",
    sourcePath: "components/bjork-ui/blocks/marketing-pricing.tsx",
    tier: "copy",
    collection: "Blocks",
    preview: "gallery",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork205",
    slug: "marketing-testimonials-wall",
    title: "Marketing testimonials wall",
    route: "/blocks/marketing-testimonials-wall",
    sourcePath: "components/bjork-ui/blocks/marketing-testimonials-wall.tsx",
    tier: "copy",
    collection: "Blocks",
    preview: "gallery",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork206",
    slug: "marketing-cta-footer",
    title: "Marketing CTA and footer",
    route: "/blocks/marketing-cta-footer",
    sourcePath: "components/bjork-ui/blocks/marketing-cta-footer.tsx",
    tier: "copy",
    collection: "Blocks",
    preview: "gallery",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork141",
    slug: "chromatic-text",
    title: "Chromatic text",
    route: "/text/chromatic-text",
    sourcePath: "components/bjork-ui/text/chromatic-text.tsx",
    tier: "copy",
    collection: "Text",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },

  {
    id: "bjork142",
    slug: "candlestick-chart",
    title: "Candlestick chart",
    route: "/charts/candlestick-chart",
    sourcePath: "components/bjork-ui/charts/candlestick-chart.tsx",
    tier: "copy",
    collection: "Charts",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork143",
    slug: "forecast-fan",
    title: "Forecast fan",
    route: "/charts/forecast-fan",
    sourcePath: "components/bjork-ui/charts/forecast-fan.tsx",
    tier: "copy",
    collection: "Charts",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork144",
    slug: "state-timeline",
    title: "State timeline",
    route: "/charts/state-timeline",
    sourcePath: "components/bjork-ui/charts/state-timeline.tsx",
    tier: "copy",
    collection: "Charts",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork145",
    slug: "spark-table",
    title: "Spark table",
    route: "/charts/spark-table",
    sourcePath: "components/bjork-ui/charts/spark-table.tsx",
    tier: "copy",
    collection: "Charts",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork146",
    slug: "distribution-plot",
    title: "Distribution plot",
    route: "/charts/distribution-plot",
    sourcePath: "components/bjork-ui/charts/distribution-plot.tsx",
    tier: "copy",
    collection: "Charts",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork147",
    slug: "violin-plot",
    title: "Violin plot",
    route: "/charts/violin-plot",
    sourcePath: "components/bjork-ui/charts/violin-plot.tsx",
    tier: "copy",
    collection: "Charts",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork148",
    slug: "beeswarm",
    title: "Beeswarm",
    route: "/charts/beeswarm",
    sourcePath: "components/bjork-ui/charts/beeswarm.tsx",
    tier: "copy",
    collection: "Charts",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork149",
    slug: "slope-chart",
    title: "Slope chart",
    route: "/charts/slope-chart",
    sourcePath: "components/bjork-ui/charts/slope-chart.tsx",
    tier: "copy",
    collection: "Charts",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork150",
    slug: "dumbbell-chart",
    title: "Dumbbell chart",
    route: "/charts/dumbbell-chart",
    sourcePath: "components/bjork-ui/charts/dumbbell-chart.tsx",
    tier: "copy",
    collection: "Charts",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork151",
    slug: "waterfall-chart",
    title: "Waterfall chart",
    route: "/charts/waterfall-chart",
    sourcePath: "components/bjork-ui/charts/waterfall-chart.tsx",
    tier: "copy",
    collection: "Charts",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork152",
    slug: "treemap",
    title: "Treemap",
    route: "/charts/treemap",
    sourcePath: "components/bjork-ui/charts/treemap.tsx",
    tier: "copy",
    collection: "Charts",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork153",
    slug: "streamgraph",
    title: "Streamgraph",
    route: "/charts/streamgraph",
    sourcePath: "components/bjork-ui/charts/streamgraph.tsx",
    tier: "copy",
    collection: "Charts",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork154",
    slug: "scatter-brush",
    title: "Scatter brush",
    route: "/charts/scatter-brush",
    sourcePath: "components/bjork-ui/charts/scatter-brush.tsx",
    tier: "copy",
    collection: "Charts",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork155",
    slug: "correlation-matrix",
    title: "Correlation matrix",
    route: "/charts/correlation-matrix",
    sourcePath: "components/bjork-ui/charts/correlation-matrix.tsx",
    tier: "copy",
    collection: "Charts",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork156",
    slug: "sankey-flow",
    title: "Sankey flow",
    route: "/charts/sankey-flow",
    sourcePath: "components/bjork-ui/charts/sankey-flow.tsx",
    tier: "copy",
    collection: "Charts",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork157",
    slug: "drawdown-chart",
    title: "Drawdown chart",
    route: "/charts/drawdown-chart",
    sourcePath: "components/bjork-ui/charts/drawdown-chart.tsx",
    tier: "copy",
    collection: "Charts",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork158",
    slug: "depth-chart",
    title: "Depth chart",
    route: "/charts/depth-chart",
    sourcePath: "components/bjork-ui/charts/depth-chart.tsx",
    tier: "copy",
    collection: "Charts",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork240",
    slug: "order-book",
    title: "Order book",
    route: "/charts/order-book",
    sourcePath: "components/bjork-ui/charts/order-book.tsx",
    tier: "copy",
    collection: "Charts",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork159",
    slug: "calibration-plot",
    title: "Calibration plot",
    route: "/charts/calibration-plot",
    sourcePath: "components/bjork-ui/charts/calibration-plot.tsx",
    tier: "copy",
    collection: "Charts",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork160",
    slug: "stacked-area-chart",
    title: "Stacked area chart",
    route: "/charts/stacked-area-chart",
    sourcePath: "components/bjork-ui/charts/stacked-area-chart.tsx",
    tier: "copy",
    collection: "Charts",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork161",
    slug: "grouped-bar-chart",
    title: "Grouped bar chart",
    route: "/charts/grouped-bar-chart",
    sourcePath: "components/bjork-ui/charts/grouped-bar-chart.tsx",
    tier: "copy",
    collection: "Charts",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork162",
    slug: "donut-chart",
    title: "Donut chart",
    route: "/charts/donut-chart",
    sourcePath: "components/bjork-ui/charts/donut-chart.tsx",
    tier: "copy",
    collection: "Charts",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork163",
    slug: "funnel-chart",
    title: "Funnel chart",
    route: "/charts/funnel-chart",
    sourcePath: "components/bjork-ui/charts/funnel-chart.tsx",
    tier: "copy",
    collection: "Charts",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork164",
    slug: "cohort-retention",
    title: "Cohort retention",
    route: "/charts/cohort-retention",
    sourcePath: "components/bjork-ui/charts/cohort-retention.tsx",
    tier: "copy",
    collection: "Charts",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork165",
    slug: "calendar-heatmap",
    title: "Calendar heatmap",
    route: "/charts/calendar-heatmap",
    sourcePath: "components/bjork-ui/charts/calendar-heatmap.tsx",
    tier: "copy",
    collection: "Charts",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork166",
    slug: "bullet-chart",
    title: "Bullet chart",
    route: "/charts/bullet-chart",
    sourcePath: "components/bjork-ui/charts/bullet-chart.tsx",
    tier: "copy",
    collection: "Charts",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork220",
    slug: "streaming-message",
    title: "Streaming message",
    route: "/ai/streaming-message",
    sourcePath: "components/bjork-ui/ai/streaming-message.tsx",
    tier: "copy",
    collection: "AI",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork221",
    slug: "reasoning-disclosure",
    title: "Reasoning disclosure",
    route: "/ai/reasoning-disclosure",
    sourcePath: "components/bjork-ui/ai/reasoning-disclosure.tsx",
    tier: "copy",
    collection: "AI",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork222",
    slug: "stream-status",
    title: "Stream status",
    route: "/ai/stream-status",
    sourcePath: "components/bjork-ui/ai/stream-status.tsx",
    tier: "copy",
    collection: "AI",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork223",
    slug: "message-branch",
    title: "Message branch",
    route: "/ai/message-branch",
    sourcePath: "components/bjork-ui/ai/message-branch.tsx",
    tier: "copy",
    collection: "AI",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork224",
    slug: "response-feedback",
    title: "Response feedback",
    route: "/ai/response-feedback",
    sourcePath: "components/bjork-ui/ai/response-feedback.tsx",
    tier: "copy",
    collection: "AI",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork225",
    slug: "prompt-composer",
    title: "Prompt composer",
    route: "/ai/prompt-composer",
    sourcePath: "components/bjork-ui/ai/prompt-composer.tsx",
    tier: "copy",
    collection: "AI",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork226",
    slug: "model-selector",
    title: "Model selector",
    route: "/ai/model-selector",
    sourcePath: "components/bjork-ui/ai/model-selector.tsx",
    tier: "copy",
    collection: "AI",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork227",
    slug: "attachment-chips",
    title: "Attachment chips",
    route: "/ai/attachment-chips",
    sourcePath: "components/bjork-ui/ai/attachment-chips.tsx",
    tier: "copy",
    collection: "AI",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork228",
    slug: "suggested-prompts",
    title: "Suggested prompts",
    route: "/ai/suggested-prompts",
    sourcePath: "components/bjork-ui/ai/suggested-prompts.tsx",
    tier: "copy",
    collection: "AI",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork229",
    slug: "context-meter",
    title: "Context meter",
    route: "/ai/context-meter",
    sourcePath: "components/bjork-ui/ai/context-meter.tsx",
    tier: "copy",
    collection: "AI",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork230",
    slug: "tool-call-card",
    title: "Tool call card",
    route: "/ai/tool-call-card",
    sourcePath: "components/bjork-ui/ai/tool-call-card.tsx",
    tier: "copy",
    collection: "AI",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork231",
    slug: "approval-gate",
    title: "Approval gate",
    route: "/ai/approval-gate",
    sourcePath: "components/bjork-ui/ai/approval-gate.tsx",
    tier: "copy",
    collection: "AI",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork232",
    slug: "diff-review",
    title: "Diff review",
    route: "/ai/diff-review",
    sourcePath: "components/bjork-ui/ai/diff-review.tsx",
    tier: "copy",
    collection: "AI",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork233",
    slug: "artifact-panel",
    title: "Artifact panel",
    route: "/ai/artifact-panel",
    sourcePath: "components/bjork-ui/ai/artifact-panel.tsx",
    tier: "copy",
    collection: "AI",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork234",
    slug: "inline-ai-edit",
    title: "Inline AI edit",
    route: "/ai/inline-ai-edit",
    sourcePath: "components/bjork-ui/ai/inline-ai-edit.tsx",
    tier: "copy",
    collection: "AI",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork235",
    slug: "citation-chips",
    title: "Citation chips",
    route: "/ai/citation-chips",
    sourcePath: "components/bjork-ui/ai/citation-chips.tsx",
    tier: "copy",
    collection: "AI",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork236",
    slug: "retrieval-inspector",
    title: "Retrieval inspector",
    route: "/ai/retrieval-inspector",
    sourcePath: "components/bjork-ui/ai/retrieval-inspector.tsx",
    tier: "copy",
    collection: "AI",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork237",
    slug: "memory-viewer",
    title: "Memory viewer",
    route: "/ai/memory-viewer",
    sourcePath: "components/bjork-ui/ai/memory-viewer.tsx",
    tier: "copy",
    collection: "AI",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork238",
    slug: "response-compare",
    title: "Response compare",
    route: "/ai/response-compare",
    sourcePath: "components/bjork-ui/ai/response-compare.tsx",
    tier: "copy",
    collection: "AI",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork239",
    slug: "cost-meter",
    title: "Cost meter",
    route: "/ai/cost-meter",
    sourcePath: "components/bjork-ui/ai/cost-meter.tsx",
    tier: "copy",
    collection: "AI",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork182",
    slug: "plan-usage-card",
    title: "Plan usage card",
    route: "/cards/plan-usage-card",
    sourcePath: "components/bjork-ui/cards/plan-usage-card.tsx",
    tier: "copy",
    collection: "Cards",
    preview: "schedule",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork183",
    slug: "payment-method-card",
    title: "Payment method card",
    route: "/cards/payment-method-card",
    sourcePath: "components/bjork-ui/cards/payment-method-card.tsx",
    tier: "copy",
    collection: "Cards",
    preview: "gallery",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork184",
    slug: "integration-card",
    title: "Integration card",
    route: "/cards/integration-card",
    sourcePath: "components/bjork-ui/cards/integration-card.tsx",
    tier: "copy",
    collection: "Cards",
    preview: "gallery",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork185",
    slug: "metric-card",
    title: "Metric card",
    route: "/cards/metric-card",
    sourcePath: "components/bjork-ui/cards/metric-card.tsx",
    tier: "copy",
    collection: "Cards",
    preview: "radial",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork186",
    slug: "shipment-card",
    title: "Shipment card",
    route: "/cards/shipment-card",
    sourcePath: "components/bjork-ui/cards/shipment-card.tsx",
    tier: "copy",
    collection: "Cards",
    preview: "schedule",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork187",
    slug: "now-playing-card",
    title: "Now playing card",
    route: "/cards/now-playing-card",
    sourcePath: "components/bjork-ui/cards/now-playing-card.tsx",
    tier: "copy",
    collection: "Cards",
    preview: "video",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork188",
    slug: "deployment-card",
    title: "Deployment card",
    route: "/cards/deployment-card",
    sourcePath: "components/bjork-ui/cards/deployment-card.tsx",
    tier: "copy",
    collection: "Cards",
    preview: "hud",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork189",
    slug: "team-invite-card",
    title: "Team invite card",
    route: "/cards/team-invite-card",
    sourcePath: "components/bjork-ui/cards/team-invite-card.tsx",
    tier: "copy",
    collection: "Cards",
    preview: "input",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork190",
    slug: "streak-card",
    title: "Streak card",
    route: "/cards/streak-card",
    sourcePath: "components/bjork-ui/cards/streak-card.tsx",
    tier: "copy",
    collection: "Cards",
    preview: "schedule",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork191",
    slug: "link-preview-card",
    title: "Link preview card",
    route: "/cards/link-preview-card",
    sourcePath: "components/bjork-ui/cards/link-preview-card.tsx",
    tier: "copy",
    collection: "Cards",
    preview: "gallery",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork212",
    slug: "app-dashboard-shell",
    title: "Dashboard shell",
    route: "/blocks/app-dashboard-shell",
    sourcePath: "components/bjork-ui/blocks/app-dashboard-shell.tsx",
    tier: "copy",
    collection: "Blocks",
    preview: "table",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork213",
    slug: "app-sign-in",
    title: "Sign in",
    route: "/blocks/app-sign-in",
    sourcePath: "components/bjork-ui/blocks/app-sign-in.tsx",
    tier: "copy",
    collection: "Blocks",
    preview: "table",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork214",
    slug: "app-settings",
    title: "Settings page",
    route: "/blocks/app-settings",
    sourcePath: "components/bjork-ui/blocks/app-settings.tsx",
    tier: "copy",
    collection: "Blocks",
    preview: "table",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork215",
    slug: "app-inbox",
    title: "Inbox",
    route: "/blocks/app-inbox",
    sourcePath: "components/bjork-ui/blocks/app-inbox.tsx",
    tier: "copy",
    collection: "Blocks",
    preview: "table",
    accent: "#ec5c13",
    isNew: true,
  },
  {
    id: "bjork216",
    slug: "app-ai-chat",
    title: "AI chat app",
    route: "/blocks/app-ai-chat",
    sourcePath: "components/bjork-ui/blocks/app-ai-chat.tsx",
    tier: "copy",
    collection: "Blocks",
    preview: "table",
    accent: "#ec5c13",
    isNew: true,
  },
];

export function getGalleryItem(slug: string) {
  return galleryItems.find((item) => item.slug === slug);
}
