export type ComponentTier = "copy" | "lab";

export interface GalleryItem {
  id: string;
  slug: string;
  title: string;
  route: string;
  sourcePath: string;
  tier: ComponentTier;
  collection: string;
  preview:
    | "radial"
    | "dock"
    | "orb"
    | "ruler"
    | "video"
    | "table"
    | "rope"
    | "input"
    | "hud"
    | "gallery"
    | "upload"
    | "schedule"
    | "shader";
  accent: string;
  isNew?: boolean;
  hasStaticPreview?: boolean;
}

export const galleryItems: GalleryItem[] = [
  {
    id: "bjork01",
    slug: "animated-radial-chart",
    title: "Animated radial chart",
    route: "/charts/animated-radial-chart",
    sourcePath: "components/isaiahbjork/charts/animated-radial-chart.tsx",
    tier: "copy",
    collection: "Charts",
    preview: "radial",
    accent: "#ec5c13",
  },
  {
    id: "bjork02",
    slug: "message-dock",
    title: "Message dock",
    route: "/hud/message-dock",
    sourcePath: "components/isaiahbjork/hud/message-dock.tsx",
    tier: "copy",
    collection: "Interactive",
    preview: "dock",
    accent: "#ec5c13",
  },
  {
    id: "bjork03",
    slug: "voice-powered-orb",
    title: "Voice powered orb",
    route: "/interactive/voice-powered-orb",
    sourcePath: "components/isaiahbjork/interactive/voice-powered-orb.tsx",
    tier: "lab",
    collection: "Interactive",
    preview: "orb",
    accent: "#ec5c13",
  },
  {
    id: "bjork04",
    slug: "ruler-carousel",
    title: "Ruler carousel",
    route: "/galleries/ruler-carousel",
    sourcePath: "components/isaiahbjork/galleries/ruler-carousel.tsx",
    tier: "copy",
    collection: "Galleries",
    preview: "ruler",
    accent: "#ec5c13",
  },
  {
    id: "bjork05",
    slug: "video-scroll-hero",
    title: "Video scroll hero",
    route: "/heroes/video-scroll-hero",
    sourcePath: "components/isaiahbjork/heroes/video-scroll-hero.tsx",
    tier: "lab",
    collection: "Heroes",
    preview: "video",
    accent: "#ec5c13",
  },
  {
    id: "bjork06",
    slug: "financial-table",
    title: "Financial table",
    route: "/tables/financial-table",
    sourcePath: "components/isaiahbjork/tables/financial-table.tsx",
    tier: "copy",
    collection: "Tables",
    preview: "table",
    accent: "#ec5c13",
  },
  {
    id: "bjork07",
    slug: "draggable-rope",
    title: "Draggable rope",
    route: "/interactive/draggable-rope",
    sourcePath: "components/isaiahbjork/interactive/draggable-rope.tsx",
    tier: "lab",
    collection: "Interactive",
    preview: "rope",
    accent: "#ec5c13",
  },
  {
    id: "bjork09",
    slug: "hud-frame",
    title: "HUD frame",
    route: "/hud/base",
    sourcePath: "components/isaiahbjork/hud/hud-frame.tsx",
    tier: "lab",
    collection: "HUD",
    preview: "hud",
    accent: "#ec5c13",
  },
  {
    id: "bjork10",
    slug: "portfolio-gallery",
    title: "Portfolio gallery",
    route: "/galleries/portfolio-gallery",
    sourcePath: "components/isaiahbjork/galleries/portfolio-gallery.tsx",
    tier: "copy",
    collection: "Galleries",
    preview: "gallery",
    accent: "#ec5c13",
  },
  {
    id: "bjork11",
    slug: "video-upload-card",
    title: "Video upload card",
    route: "/cards/video-upload-card",
    sourcePath: "components/isaiahbjork/cards/video-upload-card.tsx",
    tier: "copy",
    collection: "Cards",
    preview: "upload",
    accent: "#ec5c13",
  },
  {
    id: "bjork13",
    slug: "ai-voice-input",
    title: "AI voice input",
    route: "/ai/ai-voice-input",
    sourcePath: "components/isaiahbjork/ai/ai-voice-input.tsx",
    tier: "copy",
    collection: "AI",
    preview: "input",
    accent: "#ec5c13",
  },
  {
    id: "bjork14",
    slug: "animated-status-badge",
    title: "Animated status badge",
    route: "/badges/animated-status-badge",
    sourcePath: "components/isaiahbjork/badges/animated-status-badge.tsx",
    tier: "copy",
    collection: "Badges",
    preview: "hud",
    accent: "#ec5c13",
  },
  {
    id: "bjork15",
    slug: "animated-download",
    title: "Animated download",
    route: "/buttons/animated-download",
    sourcePath: "components/isaiahbjork/buttons/animated-download.tsx",
    tier: "copy",
    collection: "Buttons",
    preview: "upload",
    accent: "#ec5c13",
  },
  {
    id: "bjork16",
    slug: "animated-card-options",
    title: "Animated card options",
    route: "/cards/animated-card-options",
    sourcePath: "components/isaiahbjork/cards/animated-card-options.tsx",
    tier: "copy",
    collection: "Cards",
    preview: "schedule",
    accent: "#ec5c13",
  },
  {
    id: "bjork17",
    slug: "animated-card-status-list",
    title: "Animated card status list",
    route: "/cards/animated-card-status-list",
    sourcePath: "components/isaiahbjork/cards/animated-card-status-list.tsx",
    tier: "copy",
    collection: "Cards",
    preview: "schedule",
    accent: "#ec5c13",
  },
  {
    id: "bjork18",
    slug: "audio-upload-card",
    title: "Audio upload card",
    route: "/cards/audio-upload-card",
    sourcePath: "components/isaiahbjork/cards/audio-upload-card.tsx",
    tier: "copy",
    collection: "Cards",
    preview: "upload",
    accent: "#ec5c13",
  },
  {
    id: "bjork19",
    slug: "bonuses-incentives-card",
    title: "Bonuses incentives card",
    route: "/cards/bonuses-incentives-card",
    sourcePath: "components/isaiahbjork/cards/bonuses-incentives-card.tsx",
    tier: "copy",
    collection: "Cards",
    preview: "schedule",
    accent: "#ec5c13",
  },
  {
    id: "bjork20",
    slug: "coach-scheduling",
    title: "Coach scheduling",
    route: "/cards/coach-scheduling",
    sourcePath: "components/isaiahbjork/cards/coach-scheduling-card.tsx",
    tier: "copy",
    collection: "Cards",
    preview: "schedule",
    accent: "#ec5c13",
  },
  {
    id: "bjork21",
    slug: "dashboard-card-modal",
    title: "Dashboard card modal",
    route: "/cards/dashboard-card-modal",
    sourcePath: "components/isaiahbjork/cards/dashboard-card-modal.tsx",
    tier: "copy",
    collection: "Cards",
    preview: "hud",
    accent: "#ec5c13",
  },
  {
    id: "bjork22",
    slug: "event-countdown-card",
    title: "Event countdown card",
    route: "/cards/event-countdown-card",
    sourcePath: "components/isaiahbjork/cards/event-countdown-card.tsx",
    tier: "copy",
    collection: "Cards",
    preview: "schedule",
    accent: "#ec5c13",
  },
  {
    id: "bjork23",
    slug: "hover-detail-card",
    title: "Hover detail card",
    route: "/cards/hover-detail-card",
    sourcePath: "components/isaiahbjork/cards/hover-detail-card.tsx",
    tier: "copy",
    collection: "Cards",
    preview: "gallery",
    accent: "#ec5c13",
  },
  {
    id: "bjork24",
    slug: "news-cards",
    title: "News cards",
    route: "/cards/news-cards",
    sourcePath: "components/isaiahbjork/cards/news-cards.tsx",
    tier: "copy",
    collection: "Cards",
    preview: "gallery",
    accent: "#ec5c13",
  },
  {
    id: "bjork25",
    slug: "onboarding-stages",
    title: "Onboarding stages",
    route: "/cards/onboarding-stages",
    sourcePath: "components/isaiahbjork/cards/onboarding-stages.tsx",
    tier: "copy",
    collection: "Cards",
    preview: "schedule",
    accent: "#ec5c13",
  },
  {
    id: "bjork26",
    slug: "prediction-market-card",
    title: "Prediction market card",
    route: "/cards/prediction-market-card",
    sourcePath: "components/isaiahbjork/cards/prediction-market-card.tsx",
    tier: "copy",
    collection: "Cards",
    preview: "table",
    accent: "#ec5c13",
  },
  {
    id: "bjork27",
    slug: "product-reveal-card",
    title: "Product reveal card",
    route: "/cards/product-reveal-card",
    sourcePath: "components/isaiahbjork/cards/product-reveal-card.tsx",
    tier: "copy",
    collection: "Cards",
    preview: "gallery",
    accent: "#ec5c13",
  },
  {
    id: "bjork28",
    slug: "profile-hover-card",
    title: "Profile hover card",
    route: "/cards/profile-hover-card",
    sourcePath: "components/isaiahbjork/cards/profile-hover-card.tsx",
    tier: "copy",
    collection: "Cards",
    preview: "gallery",
    accent: "#ec5c13",
  },
  {
    id: "bjork29",
    slug: "project-cards",
    title: "Project cards",
    route: "/cards/project-cards",
    sourcePath: "components/isaiahbjork/cards/project-cards.tsx",
    tier: "copy",
    collection: "Cards",
    preview: "gallery",
    accent: "#ec5c13",
  },
  {
    id: "bjork31",
    slug: "gradient-selector",
    title: "Gradient selector",
    route: "/dropdowns/gradient-selector",
    sourcePath: "components/isaiahbjork/dropdowns/gradient-selector.tsx",
    tier: "copy",
    collection: "Controls",
    preview: "input",
    accent: "#ec5c13",
  },
  {
    id: "bjork32",
    slug: "hover-image-gallery",
    title: "Hover image gallery",
    route: "/galleries/hover-image-gallery",
    sourcePath: "components/isaiahbjork/galleries/hover-image-gallery.tsx",
    tier: "copy",
    collection: "Galleries",
    preview: "gallery",
    accent: "#ec5c13",
  },
  {
    id: "bjork33",
    slug: "reveal-text",
    title: "Reveal text",
    route: "/heroes/reveal-text",
    sourcePath: "components/isaiahbjork/heroes/reveal-text.tsx",
    tier: "lab",
    collection: "Text",
    preview: "video",
    accent: "#ec5c13",
  },
  {
    id: "bjork34",
    slug: "glitchy-404",
    title: "Glitchy 404",
    route: "/hud/glitchy-404",
    sourcePath: "components/isaiahbjork/hud/glitchy-404.tsx",
    tier: "lab",
    collection: "HUD",
    preview: "hud",
    accent: "#ec5c13",
  },
  {
    id: "bjork35",
    slug: "hud-2",
    title: "Overlay 2",
    route: "/hud/hud-2",
    sourcePath: "components/isaiahbjork/hud/overlay-2.tsx",
    tier: "lab",
    collection: "HUD",
    preview: "hud",
    accent: "#ec5c13",
  },
  {
    id: "bjork36",
    slug: "hud-button",
    title: "HUD button",
    route: "/hud/hud-button",
    sourcePath: "components/isaiahbjork/hud/hud-button.tsx",
    tier: "copy",
    collection: "HUD",
    preview: "hud",
    accent: "#ec5c13",
  },
  {
    id: "bjork37",
    slug: "hud-graph",
    title: "HUD graph",
    route: "/hud/hud-graph",
    sourcePath: "components/isaiahbjork/hud/graph.tsx",
    tier: "lab",
    collection: "HUD",
    preview: "radial",
    accent: "#ec5c13",
  },
  {
    id: "bjork38",
    slug: "hud-status",
    title: "HUD status",
    route: "/hud/hud-status",
    sourcePath: "components/isaiahbjork/hud/status.tsx",
    tier: "copy",
    collection: "HUD",
    preview: "hud",
    accent: "#ec5c13",
  },
  {
    id: "bjork40",
    slug: "warning-graphic",
    title: "Warning graphic",
    route: "/hud/warning-graphic",
    sourcePath: "components/isaiahbjork/hud/warning.tsx",
    tier: "lab",
    collection: "HUD",
    preview: "hud",
    accent: "#ec5c13",
  },
  {
    id: "bjork43",
    slug: "contacts-table",
    title: "Contacts table",
    route: "/tables/contacts-table",
    sourcePath: "components/isaiahbjork/tables/contacts-table.tsx",
    tier: "copy",
    collection: "Tables",
    preview: "table",
    accent: "#ec5c13",
  },
  {
    id: "bjork44",
    slug: "leads-table",
    title: "Leads table",
    route: "/tables/leads-table",
    sourcePath: "components/isaiahbjork/tables/leads-table.tsx",
    tier: "copy",
    collection: "Tables",
    preview: "table",
    accent: "#ec5c13",
  },
  {
    id: "bjork45",
    slug: "resizable-table",
    title: "Resizable table",
    route: "/tables/resizable-table",
    sourcePath: "components/isaiahbjork/tables/resizable-table.tsx",
    tier: "copy",
    collection: "Tables",
    preview: "table",
    accent: "#ec5c13",
  },
  {
    id: "bjork46",
    slug: "server-management",
    title: "Server management",
    route: "/tables/server-management",
    sourcePath: "components/isaiahbjork/tables/server-management-table.tsx",
    tier: "copy",
    collection: "Tables",
    preview: "table",
    accent: "#ec5c13",
  },
  {
    id: "bjork47",
    slug: "primitive-accordion",
    title: "Accordion",
    route: "/primitives/accordion",
    sourcePath: "components/isaiahbjork/primitives/accordion.tsx",
    tier: "copy",
    collection: "UI",
    preview: "input",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork48",
    slug: "primitive-alerts",
    title: "Alerts",
    route: "/primitives/alerts",
    sourcePath: "components/isaiahbjork/primitives/alerts.tsx",
    tier: "copy",
    collection: "UI",
    preview: "hud",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork49",
    slug: "primitive-avatar",
    title: "Avatar",
    route: "/primitives/avatar",
    sourcePath: "components/isaiahbjork/primitives/avatar.tsx",
    tier: "copy",
    collection: "UI",
    preview: "orb",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork50",
    slug: "primitive-badge",
    title: "Badge",
    route: "/primitives/badge",
    sourcePath: "components/isaiahbjork/primitives/badge.tsx",
    tier: "copy",
    collection: "UI",
    preview: "hud",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork51",
    slug: "primitive-breadcrumb",
    title: "Breadcrumb",
    route: "/primitives/breadcrumb",
    sourcePath: "components/isaiahbjork/primitives/breadcrumb.tsx",
    tier: "copy",
    collection: "UI",
    preview: "input",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork52",
    slug: "primitive-button",
    title: "Button",
    route: "/primitives/button",
    sourcePath: "components/isaiahbjork/primitives/button.tsx",
    tier: "copy",
    collection: "UI",
    preview: "input",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork53",
    slug: "primitive-button-group",
    title: "Button Group",
    route: "/primitives/button-group",
    sourcePath: "components/isaiahbjork/primitives/button-group.tsx",
    tier: "copy",
    collection: "UI",
    preview: "input",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork54",
    slug: "primitive-calendar",
    title: "Calendar",
    route: "/primitives/calendar",
    sourcePath: "components/isaiahbjork/primitives/calendar.tsx",
    tier: "copy",
    collection: "UI",
    preview: "schedule",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork55",
    slug: "primitive-card",
    title: "Card",
    route: "/primitives/card",
    sourcePath: "components/isaiahbjork/primitives/card.tsx",
    tier: "copy",
    collection: "UI",
    preview: "gallery",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork56",
    slug: "primitive-checkbox",
    title: "Checkbox",
    route: "/primitives/checkbox",
    sourcePath: "components/isaiahbjork/primitives/checkbox.tsx",
    tier: "copy",
    collection: "UI",
    preview: "input",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork57",
    slug: "primitive-collapsible",
    title: "Collapsible",
    route: "/primitives/collapsible",
    sourcePath: "components/isaiahbjork/primitives/collapsible.tsx",
    tier: "copy",
    collection: "UI",
    preview: "hud",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork58",
    slug: "primitive-combobox",
    title: "Combobox",
    route: "/primitives/combobox",
    sourcePath: "components/isaiahbjork/primitives/combobox.tsx",
    tier: "copy",
    collection: "UI",
    preview: "input",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork59",
    slug: "primitive-data-table",
    title: "Data Table",
    route: "/primitives/data-table",
    sourcePath: "components/isaiahbjork/primitives/data-table.tsx",
    tier: "copy",
    collection: "UI",
    preview: "table",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork60",
    slug: "primitive-date-picker",
    title: "Date Picker",
    route: "/primitives/date-picker",
    sourcePath: "components/isaiahbjork/primitives/date-picker.tsx",
    tier: "copy",
    collection: "UI",
    preview: "schedule",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork61",
    slug: "primitive-dialog",
    title: "Dialog",
    route: "/primitives/dialog",
    sourcePath: "components/isaiahbjork/primitives/dialog.tsx",
    tier: "copy",
    collection: "UI",
    preview: "hud",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork62",
    slug: "primitive-dropdown-menu",
    title: "Dropdown Menu",
    route: "/primitives/dropdown-menu",
    sourcePath: "components/isaiahbjork/primitives/dropdown-menu.tsx",
    tier: "copy",
    collection: "UI",
    preview: "input",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork63",
    slug: "primitive-form",
    title: "Form",
    route: "/primitives/form",
    sourcePath: "components/isaiahbjork/primitives/form.tsx",
    tier: "copy",
    collection: "UI",
    preview: "input",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork64",
    slug: "primitive-input",
    title: "Input",
    route: "/primitives/input",
    sourcePath: "components/isaiahbjork/primitives/input.tsx",
    tier: "copy",
    collection: "UI",
    preview: "input",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork65",
    slug: "primitive-input-mask",
    title: "Input Mask",
    route: "/primitives/input-mask",
    sourcePath: "components/isaiahbjork/primitives/input-mask.tsx",
    tier: "copy",
    collection: "UI",
    preview: "input",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork66",
    slug: "primitive-input-otp",
    title: "Input OTP",
    route: "/primitives/input-otp",
    sourcePath: "components/isaiahbjork/primitives/input-otp.tsx",
    tier: "copy",
    collection: "UI",
    preview: "input",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork67",
    slug: "primitive-pagination",
    title: "Pagination",
    route: "/primitives/pagination",
    sourcePath: "components/isaiahbjork/primitives/pagination.tsx",
    tier: "copy",
    collection: "UI",
    preview: "input",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork68",
    slug: "primitive-popover",
    title: "Popover",
    route: "/primitives/popover",
    sourcePath: "components/isaiahbjork/primitives/popover.tsx",
    tier: "copy",
    collection: "UI",
    preview: "hud",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork69",
    slug: "primitive-radio-group",
    title: "Radio Group",
    route: "/primitives/radio-group",
    sourcePath: "components/isaiahbjork/primitives/radio-group.tsx",
    tier: "copy",
    collection: "UI",
    preview: "input",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork70",
    slug: "primitive-select",
    title: "Select",
    route: "/primitives/select",
    sourcePath: "components/isaiahbjork/primitives/select.tsx",
    tier: "copy",
    collection: "UI",
    preview: "input",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork71",
    slug: "primitive-sheet",
    title: "Sheet",
    route: "/primitives/sheet",
    sourcePath: "components/isaiahbjork/primitives/sheet.tsx",
    tier: "copy",
    collection: "UI",
    preview: "hud",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork72",
    slug: "primitive-slider",
    title: "Slider",
    route: "/primitives/slider",
    sourcePath: "components/isaiahbjork/primitives/slider.tsx",
    tier: "copy",
    collection: "UI",
    preview: "input",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork73",
    slug: "primitive-sonner",
    title: "Sonner",
    route: "/primitives/sonner",
    sourcePath: "components/isaiahbjork/primitives/sonner.tsx",
    tier: "copy",
    collection: "UI",
    preview: "hud",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork74",
    slug: "primitive-switch",
    title: "Switch",
    route: "/primitives/switch",
    sourcePath: "components/isaiahbjork/primitives/switch.tsx",
    tier: "copy",
    collection: "UI",
    preview: "input",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork75",
    slug: "primitive-table",
    title: "Table",
    route: "/primitives/table",
    sourcePath: "components/isaiahbjork/primitives/table.tsx",
    tier: "copy",
    collection: "UI",
    preview: "table",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork76",
    slug: "primitive-tabs",
    title: "Tabs",
    route: "/primitives/tabs",
    sourcePath: "components/isaiahbjork/primitives/tabs.tsx",
    tier: "copy",
    collection: "UI",
    preview: "input",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork77",
    slug: "primitive-textarea",
    title: "Textarea",
    route: "/primitives/textarea",
    sourcePath: "components/isaiahbjork/primitives/textarea.tsx",
    tier: "copy",
    collection: "UI",
    preview: "input",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork78",
    slug: "primitive-tooltip",
    title: "Tooltip",
    route: "/primitives/tooltip",
    sourcePath: "components/isaiahbjork/primitives/tooltip.tsx",
    tier: "copy",
    collection: "UI",
    preview: "hud",
    accent: "#ec5c13",
    hasStaticPreview: false,
  },
  {
    id: "bjork80",
    slug: "shader-aurora-veil",
    title: "Aurora veil",
    route: "/shaders/aurora-veil",
    sourcePath: "components/isaiahbjork/shaders/website-shader.tsx",
    tier: "copy",
    collection: "Shaders",
    preview: "shader",
    accent: "#7bd8c4",
    hasStaticPreview: false,
  },
  {
    id: "bjork88",
    slug: "shader-kinetic-dots",
    title: "Kinetic dots",
    route: "/shaders/kinetic-dots",
    sourcePath: "components/isaiahbjork/shaders/website-shader.tsx",
    tier: "copy",
    collection: "Shaders",
    preview: "shader",
    accent: "#f0d46a",
    hasStaticPreview: false,
  },
];

export function getGalleryItem(slug: string) {
  return galleryItems.find((item) => item.slug === slug);
}
