// Share-card copy for each component: the opening of its page description,
// cut to a sentence or two so it reads whole in a link preview.
export const componentDescriptions: Record<string, string> = {
  "adaptive-precision-slider": "Drift away from the track to fine-tune. Precision comes from the body, not from a modifier key.",
  "agent-trace": "An agent's work as one rail that fills as steps finish. Slow steps turn amber, and the whole trace folds into a one-line receipt.",
  "ai-voice-input": "A chat input with voice recording overlay, waveform feedback, and message submission callbacks.",
  "animated-card-options": "A selectable option grid for AI tool pickers, onboarding steps, and dense control surfaces.",
  "animated-card-status-list": "A compact status-list card for setup flows, imports, and background sync jobs. Each row can report completed, updated, or syncing states while exposing callbacks for retry, add, and back actions.",
  "animated-download": "A download progress component with scrambled status text, file counts, remaining time, and an interruptible trigger.",
  "animated-radial-chart": "A production-grade radial progress display for dense dashboards, car-style HUDs, and high-signal metrics.",
  "animated-status-badge": "A reusable completion badge that animates behind a foreground card. Use it for queued jobs, generation states, publish flows, or any process that needs a visible running-to-complete confirmation.",
  "aperture-dive": "A hero that starts straight above a ring of screens, an eclipse, and dives into it on native scroll.",
  "api-reference-table": "A parameter reference for API docs.",
  "app-ai-chat": "A complete chat app: searchable history grouped by day, a model picker, streamed replies you can stop, light markdown with copyable code blocks, copy, feedback and regenerate on each answer…",
  "app-dashboard-shell": "An application dashboard you can paste in whole: a sidebar that collapses to an icon rail and becomes a drawer on narrow containers, a header with search, a KPI row with sparklines, a revenue…",
  "app-inbox": "A three-pane mail client: folders and labels, a searchable thread list with multi-select and bulk actions, and a reader with folded older messages and an inline reply.",
  "app-settings": "A settings page with five sections: profile with inline validation and an avatar upload, a notification matrix with quiet hours, appearance that re-themes the block as you pick, security with a…",
  "app-sign-in": "A complete sign-in and sign-up page: single sign-on, email and password with validation on blur and submit, a caps-lock warning, a password strength checklist, a passwordless link with a six-digit…",
  "approval-gate": "A human-in-the-loop check before a tool runs: the action, its target, a risk level with a reason, the arguments and side effects.",
  "artifact-panel": "A side canvas for generated work: Code and Preview tabs, a version stepper, copy, download and expand.",
  "attachment-chips": "Attached files with honest upload states: queued, uploading with a ring and percentage, indexing, ready, and failed with a retry.",
  "audio-upload-card": "An audio upload card with a compact drop zone, file metadata, and a polished upload state for media workflows.",
  "beeswarm": "Every observation as its own dot, packed beside its neighbours so none overlap and the shape of the data shows through.",
  "bonuses-incentives-card": "A bonuses and incentives card with animated circular details and expandable reward-style content.",
  "bullet-chart": "Quarter KPIs against their targets, one compact row each.",
  "calendar-heatmap": "A year of daily activity, one square per day, weeks as columns. Colour steps come from quantiles of the active days, so one record day doesn't wash out the rest, and empty days stay a quiet grey.",
  "calibration-plot": "A reliability diagram for probability forecasts. Each bin plots how often things happened against how likely they were called, with a Wilson interval, a count strip underneath and Brier and ECE above.",
  "candlestick-chart": "Daily candles with volume, a crosshair that snaps to each candle, and zoom that eases into place.",
  "changelog-table": "A release history table for developer tools. Filter by change type, search across versions and notes, and expand any release to read every change.",
  "chromatic-text": "Type that stays perfectly crisp and single-coloured until it moves.",
  "citation-chips": "Inline citation chips and a source list that know about each other. Hover or focus any chip for a preview with the quoted passage marked; the matching chips light up on both sides.",
  "click-wheel": "A rotary list selector with real angular inertia and detents you can feel.",
  "coach-scheduling": "A booking card for coaching, consultation, or service scheduling flows. Location, week navigation, and time-slot selection are all callback driven so the card can plug into real availability data.",
  "cohort-retention": "A retention triangle for signup cohorts. Each row is a cohort with its size, each column a period since signup, and each cell the share still active.",
  "contacts-table": "A contact table for people directories with row selection and compact profile metadata.",
  "context-meter": "Context window usage split by what is spending it. The bar and legend are linked, and the meter turns amber, then red, as the window fills.",
  "correlation-matrix": "A correlation heatmap on a diverging scale: positive in the accent, negative in blue, fading to the background at zero, with intensity on a power curve.",
  "cost-meter": "Spend against a budget: a figure that springs to new totals, a budget bar that turns amber at 80% and red past 100%, a per-model breakdown with cache savings, and a 14-day sparkline you can scrub…",
  "dashboard-card-modal": "A dense dashboard card with inline copy actions and a modal update path. It is built for account, policy, or record-management surfaces where the summary card needs one focused edit action.",
  "decode-text": "A scramble that resolves into real text. Each cell holds the width of its final glyph, so the line never shifts while blocks, box rules, braille or half-width katakana churn through it.",
  "deployment-card": "A deployment as it happens: the commit, a four-stage pipeline with a live timer, streaming logs that follow the tail until you scroll away, and the right action for every outcome.",
  "depth-chart": "Cumulative order book depth: bids in ink to the left of mid, asks in the accent to the right.",
  "diff-review": "Accept or reject an AI suggestion one change at a time. A line diff with word-level highlights, a resolved counter, keyboard review with j, k, a and r, and the merged text handed back when you finish.",
  "distribution-plot": "A histogram with its density curve and percentile pins. Drag the threshold, or step it with the arrow keys, and the tail past it fills with the accent while the pill reads the exact share.",
  "donut-chart": "Part-to-whole for a handful of parts. Slices run clockwise from 12 o'clock, largest first, with 2px gaps that keep their width from the hole to the rim.",
  "draggable-rope": "A GSAP Draggable rope interaction with rotation bounds, inertia, and a gravity-like return swing.",
  "drawdown-chart": "An equity curve linked to its underwater pane.",
  "dumbbell-chart": "The gap between two values for every row: a hollow ring for where it started and an accent dot for where it ended.",
  "elastic-frame": "A frame drawn as a tensioned string. Bring the pointer to an edge to pluck it, and it rings back to rest.",
  "event-countdown-card": "A compact event countdown card with animated urgency states and date-focused hierarchy.",
  "file-tree-table": "A file browser built on the ARIA treegrid pattern. Arrow keys walk and fold the tree, typing jumps by name, folders roll up their size, and sorting keeps folders on top.",
  "financial-table": "A market-index table with country flags, YTD performance, sparklines, daily movement, and selected-row state.",
  "flap-ledger": "A split-flap board for live data. Each column only flips through the characters it is allowed to show, and the cascade starts from the column that changed most.",
  "forecast-fan": "History meets forecast at a clear now line. The 50, 80 and 95% bands open out of the last real value, the median runs on as a dashed accent line, and the scrub reads every interval at once.",
  "funnel-chart": "Conversion through ordered steps, drawn as plain bars from one shared baseline so length is the count.",
  "glitchy-404": "A glitch-styled 404 graphic built for HUD pages, error states, and cinematic system screens.",
  "glow-rules": "Hairline rules that catch a soft light under the pointer. One overlay draws every rule from the items' edges, so it drops onto any list, table or grid.",
  "glyph-morph": "Words that melt into each other by shape instead of crossfading.",
  "gradient-selector": "A wide gradient selector with animated option states for choosing model durations, themes, or generated looks.",
  "grouped-bar-chart": "Categories against up to six series, grouped side by side, stacked, or stacked to 100%.",
  "handoff-beam": "A hairline of light on the bottom edge of an input. It listens, thinks and speaks.",
  "hover-detail-card": "A hover detail card for collection tiles, archive actions, and compact media metadata.",
  "hover-image-gallery": "A hover-driven image gallery for visual indexes, portfolio grids, and image-led browsing.",
  "hud-2": "A second HUD overlay flow with the animated interface background, staggered system text, menu readout, status lockup, and no outer frame chrome.",
  "hud-button": "A set of HUD-style action buttons with diagonal and hexagonal treatments. The component exposes style, variant, size, and click handlers for control panels or sci-fi interface work.",
  "hud-frame": "A cinematic HUD frame system with clipped edge geometry, optional video background, targeting overlay, status readout, and a control button for toggling the active system layer.",
  "hud-graph": "A minimal HUD area chart for telemetry, signal, or system-health surfaces. It accepts raw time-series points plus stroke, fill, dot, and scale controls for compact display contexts.",
  "hud-status": "A compact HUD status panel for system health, telemetry, and ambient operational signals.",
  "ink-bleed-text": "A word that soaks into paper. Drops land and wick outward through the fibres, the letters feather and wander while wet, then the ink dries to crisp type.",
  "inline-ai-edit": "Select text and ask AI to rewrite it. A floating toolbar offers quick edits or a free-form instruction, and the proposal streams in place over the struck original until you accept or discard it.",
  "integration-card": "Connect a third-party app. Lists the permissions it asks for, walks through the OAuth hand-off with a live handshake, then shows the account, sync state and a guarded disconnect.",
  "invoice-table": "Invoice line items with editable quantity, price, discount and tax. Totals are computed in integer minor units, so cents never drift, and the layout prints cleanly.",
  "lattice-orb": "One dot lattice that shows what an agent is doing. The dots keep their identity as the state changes.",
  "leaderboard-table": "A ranked leaderboard with rank movement, score against the leader and win streaks.",
  "leads-table": "A leads management table with live interest sparklines, probability signals, selected-row actions, and simulated data movement.",
  "link-preview-card": "An Open Graph unfurl for chat, docs and composers.",
  "liquid-text": "Type as a viscous surface. Drag across a letter and a sprung trail of blobs pulls a bead of ink off it; let go and surface tension snaps it back into the stroke.",
  "live-line": "A streaming line chart that stays calm. Values glide in on a damped head, the y range never clips a spike and contracts slowly, and the newest value is always labelled.",
  "magnetic-letters": "Letters on damped springs that lean toward the cursor or shy away from it, tilting and scaling as they go.",
  "marketing-cta-footer": "The end of a landing page in one block: a closing call to action with an install command you can copy, then the footer with link columns, a newsletter form that validates and confirms, a live…",
  "marketing-feature-bento": "A feature section on a bento grid where every card explains itself.",
  "marketing-hero-product": "A landing-page hero with a product shot that is actually alive.",
  "marketing-pricing": "A pricing section with a monthly and annual toggle, plan cards whose prices roll to the new period, and a full feature comparison that opens underneath.",
  "marketing-testimonials-wall": "A wall of customer quotes with the numbers that back them up.",
  "memory-viewer": "Everything the assistant remembers, grouped and searchable. Edit a memory in place, or forget it with five seconds to undo.",
  "message-branch": "A chat message with versions. Step between branches with the switcher or the arrow keys, copy, regenerate an answer or edit a prompt into a new branch, and the thread never jumps.",
  "message-dock": "A compact character dock that expands into a focused message composer.",
  "metric-card": "A KPI tile: headline value, delta against the previous period and a sparkline you can scrub with the pointer or the arrow keys.",
  "minimap-scrollbar": "A scroll rail that shows where you are in the document and how it is built. Ticks mark headings and blocks, and the heading under your pointer appears in a label.",
  "model-selector": "A model picker with search, providers as groups, and the numbers that matter on every row: capabilities, context window, speed and price.",
  "morph-loader": "A spinner whose segments become the result. When the work finishes, the ring re-forms into a check, a cross or your own glyph.",
  "mosaic-settle": "An image frame that owns its loading state. A churning mosaic resolves cell by cell into the photo, then gets out of the way.",
  "news-cards": "A responsive news card set with animated editorial cards and stacked content rhythm.",
  "now-playing-card": "A now-playing card with a generated cover, scrubbable progress, transport controls, like and the next track.",
  "onboarding-stages": "A progress card for onboarding, launch checklists, and account setup flows.",
  "order-book": "A live bid and ask ladder with cumulative depth bars, spread and last price, price grouping and change flashes. Streams snapshots and deltas a frame at a time, and clicking a level hands its price to your order form.",
  "page.tsx": "Components, shader studies, and product-grade interface fragments grouped by collection.",
  "payment-method-card": "Saved payment methods. The selected card tilts under the pointer and flips for billing details; the list below picks, defaults and removes cards and flags expired or expiring ones.",
  "periodic-table": "A full periodic table with spring-physics hover cards that blur in from below each element.",
  "permissions-matrix": "A roles by permissions matrix for access control.",
  "plan-usage-card": "Plan usage for the current billing cycle. Each meter projects its cycle-end total from the pace so far, warns before a limit is hit and says what happens past it.",
  "plane-type": "Display type set as overlapping planes in space. Lines slide past each other as you move.",
  "portfolio-gallery": "A layered image gallery with overlapping desktop cards, hover lift, and mobile marquee fallback.",
  "prediction-market-card": "A prediction market card with betting-style probability, market metadata, and action surfaces.",
  "pricing-table": "A plan comparison table for pricing pages.",
  "primitive-accordion": "A stacked disclosure control for expanding one section of supporting content without leaving the page.",
  "primitive-alerts": "A compact status callout for surfacing important feedback with a title and supporting message.",
  "primitive-avatar": "A live shader avatar for identity anchors that need motion without relying on user photos.",
  "primitive-badge": "A compact status label for state, category, and metadata markers in dense interfaces.",
  "primitive-breadcrumb": "A low-emphasis navigation trail for showing where the current page sits in a hierarchy.",
  "primitive-button": "A tactile action button with variants for primary, secondary, utility, and icon-only controls.",
  "primitive-button-group": "A joined control group for related actions that should read as one toolbar.",
  "primitive-calendar": "A single-month date selector for scheduling flows, filters, and date-picking popovers.",
  "primitive-card": "A composable content surface for grouping headers, metrics, media, and actions.",
  "primitive-checkbox": "A binary selection control for preferences, filters, and table rows.",
  "primitive-collapsible": "A disclosure wrapper for revealing optional details inside the current surface.",
  "primitive-combobox": "A searchable picker for choosing one option from a longer list.",
  "primitive-command-palette": "A global Command-K search surface for routing across pages, primitives, components, and app actions.",
  "primitive-data-table": "A filterable table pattern for scanning records and narrowing operational data.",
  "primitive-date-picker": "An anchored calendar trigger for selecting a single date without opening a full modal.",
  "primitive-dialog": "A centered modal surface for decisions that require the user's focused attention.",
  "primitive-dropdown-menu": "A compact action menu for secondary commands tied to a button or row.",
  "primitive-form": "A compact form pattern for editing a small set of account or profile fields.",
  "primitive-input": "A text-entry field for forms, search shells, filters, and validation states.",
  "primitive-input-mask": "A formatted text field for structured numeric values that need grouped spacing.",
  "primitive-input-otp": "A segmented one-time-code input for short verification flows.",
  "primitive-pagination": "A page navigation control for moving through long result sets without losing context.",
  "primitive-popover": "An anchored overlay for short supporting content, filters, or inline controls.",
  "primitive-radio-group": "A single-choice selector for mutually exclusive options with clear row targets.",
  "primitive-select": "A compact option picker for short lists where search is unnecessary.",
  "primitive-sheet": "A side panel for secondary workflows that should keep the current page visible.",
  "primitive-slider": "A range control for tuning numeric values with immediate visual feedback.",
  "primitive-sonner": "A toast notification trigger for confirming non-blocking actions.",
  "primitive-switch": "A binary toggle for persistent on-or-off settings.",
  "primitive-table": "A structured data surface for comparing rows of account, status, or metric information.",
  "primitive-tabs": "A segmented content switcher for parallel views that share one footprint.",
  "primitive-textarea": "A multi-line text field for notes, descriptions, and longer user input.",
  "primitive-tooltip": "A hover and focus hint for icon-only controls or compact labels.",
  "product-reveal-card": "A product reveal card for hover-led product storytelling, feature peeks, and compact commerce surfaces.",
  "profile-hover-card": "A profile card with hover affordances for people grids, team views, and social surfaces.",
  "project-cards": "Expandable project cards for marketplaces, work boards, or internal assignment queues. Each card keeps the scan-friendly summary visible and progressively reveals detail on selection.",
  "project-index": "A ledger of work. Titles sit on the left; on hover a dossier card rises from the bottom right and holds still while you move between rows, dissolving its media and swapping only what changes.",
  "prompt-composer": "A chat input that grows with its text, takes files by button, paste or drop, opens a command list on “/”, and turns send into stop while a reply streams.",
  "radial-command-ring": "Hold anywhere and flick toward an action. You choose by direction, not by hitting a target.",
  "reasoning-disclosure": "A model's reasoning as a quiet disclosure. The label shimmers and the seconds count while it streams into a capped, self-scrolling viewport, then it settles into “Thought for 12s” and folds away.",
  "resizable-table": "A resizable employee table with draggable column widths, row selection, and dense dashboard formatting.",
  "response-compare": "Two answers to one prompt, side by side, with latency, tokens and cost. Vote with a radio group, mark a rubric per side, and blind model names reveal once the vote is in.",
  "response-feedback": "Thumbs up and down for an AI answer. A rating opens a short panel of reasons and an optional comment, then folds into a quiet receipt you can undo.",
  "retrieval-inspector": "A debug view for retrieval: the query and model, then each chunk with its source, similarity, rerank move, token cost and whether the answer used it.",
  "reveal-text": "A large reveal text animation with delayed overlay motion for title treatments and motion studies.",
  "route-trace": "A live system diagram routed like a circuit board. Traffic shows as packets, and failure shows as silence.",
  "ruler-carousel": "A tactile horizontal carousel with ruler marks, infinite item wrapping, keyboard controls, and a centered active item.",
  "sankey-flow": "Flows between stages, sized by volume and laid out to keep ribbons from crossing. Hover a node or a ribbon and its whole path, upstream and down, lights in the accent while everything else steps back.",
  "scatter-brush": "Fifteen hundred points on one canvas. Drag out a region to select it: the selection takes the accent, everything else falls back, and the marginal histograms and the readout follow live.",
  "scatter-rewind": "A headline that blows away as type dust and rebuilds by running time backwards, along the same paths.",
  "scene-states": "Sections declare camera poses with data attributes and scroll blends between them.",
  "server-management": "A server management table with live CPU bars, country metadata, status controls, and infrastructure-style row density.",
  "shader-aurora-veil": "A compact, single-draw WebGL shader for website backdrops, hero accents, cards, and product moments.",
  "shader-kinetic-dots": "A compact, single-draw WebGL shader for website backdrops, hero accents, cards, and product moments.",
  "shipment-card": "Order tracking at a glance: when it arrives, where it is on the way, what is inside and the full scan history on demand.",
  "shortcuts-table": "A keyboard shortcut reference. It picks Mac or Windows and Linux keys from the browser, lets the reader switch, and filters as you type by action or by key name, lighting up the matching keycaps.",
  "sidebar-08": "An inset application sidebar with nested navigation, projects, secondary links, a user menu, and a collapsible content area.",
  "slice-shift": "A headline cut into horizontal strips.",
  "slope-chart": "Before and after for every item, one line each. End labels spread apart when values crowd and keep a leader line back to their point.",
  "solar-sky-panel": "A sky card lit by the real sun for any place and time. Scrub the day with your finger.",
  "sortable-table": "A typed data table for dashboards. Search across visible columns, sort by one column or shift-click for several, hide columns, select rows and page through results, all from the keyboard.",
  "spark-table": "A metrics table where every row carries its own sparkline and every sparkline shares one crosshair.",
  "spec-sheet": "A product spec sheet that compares up to three models side by side.",
  "spreadsheet-grid": "A spreadsheet built on the ARIA grid pattern.",
  "spring-tuner": "Tune a spring by grabbing its overshoot, see it run, and copy the exact config.",
  "stacked-area-chart": "A total split into its parts over time. Each band sits on the one below with a thin seam between them, and the crosshair reads every part and the total for one day.",
  "state-timeline": "Lanes of states over time with an overview brush underneath. Healthy time stays quiet so incidents stand out.",
  "streak-card": "A habit streak: the current run, this week at a glance, a heatmap you can walk with the arrow keys, the next milestone and a check-in that celebrates once.",
  "stream-status": "One quiet line for a long AI wait. The phase slides in as it changes, a clock and step count keep time, a hairline shows progress, and the line settles into a receipt for done, failed or stopped.",
  "streamgraph": "Layers flowing around a centre line, ordered inside out so the big steady layers sit in the middle and the seasonal ones ride the edges.",
  "streaming-message": "Assistant markdown that renders as it streams. Half-typed markup never flashes, an unclosed fence is already a code block, and only the last block re-renders per chunk.",
  "stroke-draw-type": "Outline type that draws itself with a small glowing pen tip, then fills from below like liquid rising.",
  "stroke-morph-icon": "An icon set where every glyph is three lines, so any icon can become any other as one object.",
  "suggested-prompts": "Starter prompts for an empty chat and follow-up chips after an answer.",
  "team-invite-card": "Invite people by email: paste or type a list, pick a role and send. Bad addresses, existing members and seat limits are caught before sending; pending invites can be resent or revoked.",
  "timer": "A countdown instrument: rolling digits on a hairline dial. Drag the dial or the digits to set time, use the presets, and run it from the keyboard.",
  "timetable": "A weekly timetable for agendas, class schedules and room bookings. Overlapping sessions share the slot side by side, a now line tracks the current day, and track chips filter the week.",
  "tool-call-card": "One tool invocation as a quiet row: status, name, summary and a live duration. It opens to tinted JSON input and output, with copy buttons and long results clamped.",
  "torn-edge-reveal": "Any image or card gets a hand-torn paper edge, generated from a seed. The tear rips in once and holds.",
  "transactions-table": "Order history grouped by day. Filter by status with live counts, open a row to see its line items, and pick an order to inspect it.",
  "treemap": "Squarified tiles, sized by value and coloured by change: accent for gains and blue for losses, both stronger with size of move and fading to the background at zero.",
  "velocity-ink": "Sign with ink whose width follows your hand speed. Export the stroke as SVG, or type instead.",
  "video-scroll-hero": "A scroll-reactive video hero that scales a media surface from a small cinematic frame into a full hero moment.",
  "video-upload-card": "A video upload card with click-to-select, drag-over state, upload simulation, and inline video preview.",
  "violin-plot": "Groups drawn as violins, boxes or raw strips, and the shapes morph between the three views rather than swapping.",
  "voice-powered-orb": "A WebGL voice-reactive orb built with OGL. It renders a fragment shader on a full canvas and can optionally listen to microphone amplitude to modulate motion intensity.",
  "warning-graphic": "A warning graphic for alert states, system panels, and high-contrast HUD overlays.",
  "waterfall-chart": "A P&L bridge from gross to net. Each step grows out of the running total before it, dashed connectors carry the level across, and losses read as hatched outlines rather than a second colour.",
  "weight-wave": "A line of Geist whose weight axis swells under the cursor with a gaussian falloff. When the pointer is away, a crest of weight travels the line on its own.",
};
